window.teams = [
  {
    "name": "New York Knicks",
    "state": "NY",
    "colors": "Blue/Orange",
    "titles": 2,
    "lastTitle": 1973,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg"
  },
  {
    "name": "Boston Celtics",
    "state": "MA",
    "colors": "Black/Green",
    "titles": 18,
    "lastTitle": 2024,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg"
  },
  {
    "name": "Brooklyn Nets",
    "state": "NY",
    "colors": "Black/Gray",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg"
  },
  {
    "name": "Charlotte Hornets",
    "state": "NC",
    "colors": "Purple/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg"
  },
  {
    "name": "Chicago Bulls",
    "state": "IL",
    "colors": "Black/Red",
    "titles": 6,
    "lastTitle": 1998,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg"
  },
  {
    "name": "Cleveland Cavaliers",
    "state": "OH",
    "colors": "Red/Yellow",
    "titles": 1,
    "lastTitle": 2016,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg"
  },
  {
    "name": "Atlanta Hawks",
    "state": "GA",
    "colors": "Red/Yellow",
    "titles": 1,
    "lastTitle": 1958,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg"
  },
  {
    "name": "Dallas Mavericks",
    "state": "TX",
    "colors": "Blue/Gray",
    "titles": 1,
    "lastTitle": 2011,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg"
  },
  {
    "name": "Denver Nuggets",
    "state": "CO",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 2023,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg"
  },
  {
    "name": "Detroit Pistons",
    "state": "MI",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 2004,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg"
  },
  {
    "name": "Golden State Warriors",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 7,
    "lastTitle": 2022,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg"
  },
  {
    "name": "Houston Rockets",
    "state": "TX",
    "colors": "Black/Red",
    "titles": 2,
    "lastTitle": 1995,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg"
  },
  {
    "name": "Indiana Pacers",
    "state": "IN",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg"
  },
  {
    "name": "Los Angeles Clippers",
    "state": "CA",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg"
  },
  {
    "name": "Los Angeles Lakers",
    "state": "CA",
    "colors": "Purple/Yellow",
    "titles": 17,
    "lastTitle": 2020,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg"
  },
  {
    "name": "Memphis Grizzlies",
    "state": "TN",
    "colors": "Blue/Gray",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg"
  },
  {
    "name": "Miami Heat",
    "state": "FL",
    "colors": "Black/Red",
    "titles": 3,
    "lastTitle": 2013,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg"
  },
  {
    "name": "Milwaukee Bucks",
    "state": "WI",
    "colors": "Green/White",
    "titles": 2,
    "lastTitle": 2021,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg"
  },
  {
    "name": "Minnesota Timberwolves",
    "state": "MN",
    "colors": "Blue/Gray",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg"
  },
  {
    "name": "New Orleans Pelicans",
    "state": "LA",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg"
  },
  {
    "name": "Oklahoma City Thunder",
    "state": "OK",
    "colors": "Blue/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg"
  },
  {
    "name": "Orlando Magic",
    "state": "FL",
    "colors": "Black/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg"
  },
  {
    "name": "Philadelphia 76ers",
    "state": "PA",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 1983,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg"
  },
  {
    "name": "Phoenix Suns",
    "state": "AZ",
    "colors": "Purple/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg"
  },
  {
    "name": "Portland Trail Blazers",
    "state": "OR",
    "colors": "Black/Red",
    "titles": 1,
    "lastTitle": 1977,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg"
  },
  {
    "name": "Sacramento Kings",
    "state": "CA",
    "colors": "Purple/Gray",
    "titles": 1,
    "lastTitle": 1951,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg"
  },
  {
    "name": "San Antonio Spurs",
    "state": "TX",
    "colors": "Black/Gray",
    "titles": 5,
    "lastTitle": 2014,
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg"
  },
  {
    "name": "Toronto Raptors",
    "state": "ON",
    "colors": "Black/Red",
    "titles": 1,
    "lastTitle": 2019,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg"
  },
  {
    "name": "Utah Jazz",
    "state": "UT",
    "colors": "Purple/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NBA",
    "conference": "Western",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg"
  },
  {
    "name": "Washington Wizards",
    "state": "DC",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 1978,
    "league": "NBA",
    "conference": "Eastern",
    "sport": "Basketball",
    "logo": "https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg"
  },
  {
    "name": "Arizona Cardinals",
    "state": "AZ",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/u9fltoslqdsyao8cpm0k"
  },
  {
    "name": "Atlanta Falcons",
    "state": "GA",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op"
  },
  {
    "name": "Baltimore Ravens",
    "state": "MD",
    "colors": "Black/Purple",
    "titles": 2,
    "lastTitle": 2012,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ucsdijmddsqcj1i9tddd"
  },
  {
    "name": "Buffalo Bills",
    "state": "NY",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/giphcy6ie9mxbnldntsf"
  },
  {
    "name": "Carolina Panthers",
    "state": "NC",
    "colors": "Black/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq"
  },
  {
    "name": "Chicago Bears",
    "state": "IL",
    "colors": "Blue/Orange",
    "titles": 1,
    "lastTitle": 1985,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ijrplti0kmzsyoaikhv1"
  },
  {
    "name": "Cincinnati Bengals",
    "state": "OH",
    "colors": "Black/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/okxpteoliyayufypqalq"
  },
  {
    "name": "Cleveland Browns",
    "state": "OH",
    "colors": "Brown/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/upload/f_auto/league/bedyixmmjhszfcx5wv2l"
  },
  {
    "name": "Dallas Cowboys",
    "state": "TX",
    "colors": "Blue/Gray",
    "titles": 5,
    "lastTitle": 1995,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ieid8hoygzdlmzo0tnf6"
  },
  {
    "name": "Denver Broncos",
    "state": "CO",
    "colors": "Orange/Blue",
    "titles": 3,
    "lastTitle": 2015,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/t0p7m5cjdjy18rnzzqbx"
  },
  {
    "name": "Detroit Lions",
    "state": "MI",
    "colors": "Blue/Gray",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ocvxwnapdvwevupe4tpr"
  },
  {
    "name": "Green Bay Packers",
    "state": "WI",
    "colors": "Green/Yellow",
    "titles": 4,
    "lastTitle": 2010,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/gppfvr7n8gljgjaqux2x"
  },
  {
    "name": "Houston Texans",
    "state": "TX",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/upload/f_auto/league/u6camnphqvjc6mku6u3c"
  },
  {
    "name": "Indianapolis Colts",
    "state": "IN",
    "colors": "Blue/White",
    "titles": 2,
    "lastTitle": 2006,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ketwqeuschqzjsllbid5"
  },
  {
    "name": "Jacksonville Jaguars",
    "state": "FL",
    "colors": "Black/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/qycbib6ivrm9dqaexryk"
  },
  {
    "name": "Kansas City Chiefs",
    "state": "MO",
    "colors": "Red/Yellow",
    "titles": 3,
    "lastTitle": 2024,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ujshjqvmnxce8m4obmvs"
  },
  {
    "name": "Las Vegas Raiders",
    "state": "NV",
    "colors": "Black/Gray",
    "titles": 3,
    "lastTitle": 1983,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/gzcojbzcyjgubgyb6xf2"
  },
  {
    "name": "Los Angeles Chargers",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/dhfidtn8jrumakbogeu4"
  },
  {
    "name": "Los Angeles Rams",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 2,
    "lastTitle": 2021,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/ayvwcmluj2ohkdlbiegi"
  },
  {
    "name": "Miami Dolphins",
    "state": "FL",
    "colors": "Blue/Orange",
    "titles": 2,
    "lastTitle": 1973,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/lits6p8ycthy9to70bnt"
  },
  {
    "name": "Minnesota Vikings",
    "state": "MN",
    "colors": "Purple/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/teguylrnqqmfcwxvcmmz"
  },
  {
    "name": "New England Patriots",
    "state": "MA",
    "colors": "Blue/Gray",
    "titles": 6,
    "lastTitle": 2018,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/moyfxx3dq5pio4aiftnc"
  },
  {
    "name": "New Orleans Saints",
    "state": "LA",
    "colors": "Black/White",
    "titles": 1,
    "lastTitle": 2009,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx"
  },
  {
    "name": "New York Giants",
    "state": "NY",
    "colors": "Blue/Red",
    "titles": 4,
    "lastTitle": 2011,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/New_York_Giants_logo.svg/2560px-New_York_Giants_logo.svg.png"
  },
  {
    "name": "New York Jets",
    "state": "NY",
    "colors": "Green/White",
    "titles": 1,
    "lastTitle": 1968,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/New_York_Jets_2024.svg/1200px-New_York_Jets_2024.svg.png"
  },
  {
    "name": "Philadelphia Eagles",
    "state": "PA",
    "colors": "Green/Gray",
    "titles": 2,
    "lastTitle": 2025,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/puhrqgj71gobgdkdo6uq"
  },
  {
    "name": "Pittsburgh Steelers",
    "state": "PA",
    "colors": "Black/Yellow",
    "titles": 6,
    "lastTitle": 2008,
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx"
  },
  {
    "name": "San Francisco 49ers",
    "state": "CA",
    "colors": "Red/White",
    "titles": 5,
    "lastTitle": 1994,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn"
  },
  {
    "name": "Seattle Seahawks",
    "state": "WA",
    "colors": "Blue/Green",
    "titles": 1,
    "lastTitle": 2013,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/gcytzwpjdzbpwnwxincg"
  },
  {
    "name": "Tampa Bay Buccaneers",
    "state": "FL",
    "colors": "Red/Gray",
    "titles": 2,
    "lastTitle": 2020,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih"
  },
  {
    "name": "Tennessee Titans",
    "state": "TN",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NFL",
    "conference": "AFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/pln44vuzugjgipyidsre"
  },
  {
    "name": "Washington Commanders",
    "state": "DC",
    "colors": "Red/Yellow",
    "titles": 3,
    "lastTitle": 1991,
    "league": "NFL",
    "conference": "NFC",
    "sport": "Football",
    "logo": "https://static.www.nfl.com/image/private/f_auto/league/xymxwrxtyj9fhaemhdyd"
  },
  {
    "name": "Arizona Diamondbacks",
    "state": "AZ",
    "colors": "Black/Red",
    "titles": 1,
    "lastTitle": 2001,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/109.svg"
  },
  {
    "name": "Atlanta Braves",
    "state": "GA",
    "colors": "Blue/Red",
    "titles": 4,
    "lastTitle": 2021,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/144.svg"
  },
  {
    "name": "Baltimore Orioles",
    "state": "MD",
    "colors": "Black/Orange",
    "titles": 3,
    "lastTitle": 1983,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/110.svg"
  },
  {
    "name": "Boston Red Sox",
    "state": "MA",
    "colors": "Blue/Red",
    "titles": 9,
    "lastTitle": 2018,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/111.svg"
  },
  {
    "name": "Chicago White Sox",
    "state": "IL",
    "colors": "Black/White",
    "titles": 3,
    "lastTitle": 2005,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/145.svg"
  },
  {
    "name": "Chicago Cubs",
    "state": "IL",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 2016,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/112.svg"
  },
  {
    "name": "Cincinnati Reds",
    "state": "OH",
    "colors": "Red/White",
    "titles": 5,
    "lastTitle": 1990,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/113.svg"
  },
  {
    "name": "Cleveland Guardians",
    "state": "OH",
    "colors": "Blue/Red",
    "titles": 2,
    "lastTitle": 1948,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/114.svg"
  },
  {
    "name": "Colorado Rockies",
    "state": "CO",
    "colors": "Black/Purple",
    "titles": 0,
    "lastTitle": "None",
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/115.svg"
  },
  {
    "name": "Detroit Tigers",
    "state": "MI",
    "colors": "Blue/Orange",
    "titles": 4,
    "lastTitle": 1984,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/116.svg"
  },
  {
    "name": "Houston Astros",
    "state": "TX",
    "colors": "Blue/Orange",
    "titles": 2,
    "lastTitle": 2022,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-primary-on-light/117.svg"
  },
  {
    "name": "Kansas City Royals",
    "state": "MO",
    "colors": "Blue/White",
    "titles": 2,
    "lastTitle": 2015,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/118.svg"
  },
  {
    "name": "Los Angeles Angels",
    "state": "CA",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 2002,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/108.svg"
  },
  {
    "name": "Los Angeles Dodgers",
    "state": "CA",
    "colors": "Blue/White",
    "titles": 8,
    "lastTitle": 2024,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/119.svg"
  },
  {
    "name": "Miami Marlins",
    "state": "FL",
    "colors": "Black/Blue",
    "titles": 2,
    "lastTitle": 2003,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/146.svg"
  },
  {
    "name": "Milwaukee Brewers",
    "state": "WI",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/158.svg"
  },
  {
    "name": "Minnesota Twins",
    "state": "MN",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 1991,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/142.svg"
  },
  {
    "name": "New York Mets",
    "state": "NY",
    "colors": "Blue/Orange",
    "titles": 2,
    "lastTitle": 1986,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/121.svg"
  },
  {
    "name": "New York Yankees",
    "state": "NY",
    "colors": "Blue/White",
    "titles": 27,
    "lastTitle": 2009,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/147.svg"
  },
  {
    "name": "Oakland Athletics",
    "state": "CA",
    "colors": "Green/Yellow",
    "titles": 9,
    "lastTitle": 1989,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/133.svg"
  },
  {
    "name": "Philadelphia Phillies",
    "state": "PA",
    "colors": "Red/White",
    "titles": 2,
    "lastTitle": 2008,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/143.svg"
  },
  {
    "name": "Pittsburgh Pirates",
    "state": "PA",
    "colors": "Black/Yellow",
    "titles": 5,
    "lastTitle": 1979,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/134.svg"
  },
  {
    "name": "San Diego Padres",
    "state": "CA",
    "colors": "Brown/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/135.svg"
  },
  {
    "name": "San Francisco Giants",
    "state": "CA",
    "colors": "Black/Orange",
    "titles": 8,
    "lastTitle": 2014,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/137.svg"
  },
  {
    "name": "Seattle Mariners",
    "state": "WA",
    "colors": "Blue/Green",
    "titles": 0,
    "lastTitle": "None",
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-primary-on-light/136.svg"
  },
  {
    "name": "St. Louis Cardinals",
    "state": "MO",
    "colors": "Blue/Red",
    "titles": 11,
    "lastTitle": 2011,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/138.svg"
  },
  {
    "name": "Tampa Bay Rays",
    "state": "FL",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/139.svg"
  },
  {
    "name": "Texas Rangers",
    "state": "TX",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 2023,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/140.svg"
  },
  {
    "name": "Toronto Blue Jays",
    "state": "ON",
    "colors": "Blue/Red",
    "titles": 2,
    "lastTitle": 1993,
    "league": "MLB",
    "conference": "American",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/141.svg"
  },
  {
    "name": "Washington Nationals",
    "state": "DC",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 2019,
    "league": "MLB",
    "conference": "National",
    "sport": "Baseball",
    "logo": "https://www.mlbstatic.com/team-logos/team-cap-on-light/120.svg"
  },
  {
    "name": "Anaheim Ducks",
    "state": "CA",
    "colors": "Black/Orange",
    "titles": 1,
    "lastTitle": 2007,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/ANA_dark.svg"
  },
  {
    "name": "Utah Mammoth",
    "state": "UT",
    "colors": "Black/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/UTA_dark.svg"
  },
  {
    "name": "Boston Bruins",
    "state": "MA",
    "colors": "Black/Yellow",
    "titles": 6,
    "lastTitle": 2011,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg"
  },
  {
    "name": "Buffalo Sabres",
    "state": "NY",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg"
  },
  {
    "name": "Calgary Flames",
    "state": "AB",
    "colors": "Red/Yellow",
    "titles": 1,
    "lastTitle": 1989,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/CGY_dark.svg"
  },
  {
    "name": "Carolina Hurricanes",
    "state": "NC",
    "colors": "Black/Red",
    "titles": 1,
    "lastTitle": 2006,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg"
  },
  {
    "name": "Chicago Blackhawks",
    "state": "IL",
    "colors": "Black/Red",
    "titles": 6,
    "lastTitle": 2015,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg"
  },
  {
    "name": "Colorado Avalanche",
    "state": "CO",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 2022,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/COL_dark.svg"
  },
  {
    "name": "Columbus Blue Jackets",
    "state": "OH",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/CBJ_dark.svg"
  },
  {
    "name": "Dallas Stars",
    "state": "TX",
    "colors": "Black/Green",
    "titles": 1,
    "lastTitle": 1999,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg"
  },
  {
    "name": "Detroit Red Wings",
    "state": "MI",
    "colors": "Red/White",
    "titles": 11,
    "lastTitle": 2008,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/DET_dark.svg"
  },
  {
    "name": "Edmonton Oilers",
    "state": "AB",
    "colors": "Blue/Orange",
    "titles": 5,
    "lastTitle": 1990,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/EDM_dark.svg"
  },
  {
    "name": "Florida Panthers",
    "state": "FL",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 2024,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/FLA_dark.svg"
  },
  {
    "name": "Los Angeles Kings",
    "state": "CA",
    "colors": "Black/Gray",
    "titles": 2,
    "lastTitle": 2014,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/LAK_dark.svg"
  },
  {
    "name": "Minnesota Wild",
    "state": "MN",
    "colors": "Green/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg"
  },
  {
    "name": "Montreal Canadiens",
    "state": "QC",
    "colors": "Blue/Red",
    "titles": 24,
    "lastTitle": 1993,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg"
  },
  {
    "name": "Nashville Predators",
    "state": "TN",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/NSH_dark.svg"
  },
  {
    "name": "New Jersey Devils",
    "state": "NJ",
    "colors": "Black/Red",
    "titles": 3,
    "lastTitle": 2003,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/NJD_dark.svg"
  },
  {
    "name": "New York Islanders",
    "state": "NY",
    "colors": "Blue/Orange",
    "titles": 4,
    "lastTitle": 1983,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/NYI_dark.svg"
  },
  {
    "name": "New York Rangers",
    "state": "NY",
    "colors": "Blue/Red",
    "titles": 4,
    "lastTitle": 1994,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg"
  },
  {
    "name": "Ottawa Senators",
    "state": "ON",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg"
  },
  {
    "name": "Philadelphia Flyers",
    "state": "PA",
    "colors": "Black/Orange",
    "titles": 2,
    "lastTitle": 1975,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/PHI_dark.svg"
  },
  {
    "name": "Pittsburgh Penguins",
    "state": "PA",
    "colors": "Black/Yellow",
    "titles": 5,
    "lastTitle": 2017,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg"
  },
  {
    "name": "San Jose Sharks",
    "state": "CA",
    "colors": "Black/Blue",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/SJS_dark.svg"
  },
  {
    "name": "Seattle Kraken",
    "state": "WA",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/SEA_dark.svg"
  },
  {
    "name": "St. Louis Blues",
    "state": "MO",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 2019,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/STL_dark.svg"
  },
  {
    "name": "Tampa Bay Lightning",
    "state": "FL",
    "colors": "Black/Blue",
    "titles": 3,
    "lastTitle": 2021,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg"
  },
  {
    "name": "Toronto Maple Leafs",
    "state": "ON",
    "colors": "Blue/White",
    "titles": 13,
    "lastTitle": 1967,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg"
  },
  {
    "name": "Vancouver Canucks",
    "state": "BC",
    "colors": "Blue/Green",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/VAN_dark.svg"
  },
  {
    "name": "Vegas Golden Knights",
    "state": "NV",
    "colors": "Black/Yellow",
    "titles": 1,
    "lastTitle": 2023,
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/VGK_dark.svg"
  },
  {
    "name": "Washington Capitals",
    "state": "DC",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 2018,
    "league": "NHL",
    "conference": "Eastern",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/WSH_dark.svg"
  },
  {
    "name": "Winnipeg Jets",
    "state": "MB",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NHL",
    "conference": "Western",
    "sport": "Hockey",
    "logo": "https://assets.nhle.com/logos/nhl/svg/WPG_dark.svg"
  },
  {
    "name": "Indiana Hoosiers Basketball",
    "state": "IN",
    "colors": "Red/White",
    "titles": 5,
    "lastTitle": 1987,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt642e368419deffde/652e7097926e8748efdf617e/Indiana.svg?width=25&auto=webpll"
  },
  {
    "name": "Michigan State Spartans Basketball",
    "state": "MI",
    "colors": "Green/White",
    "titles": 2,
    "lastTitle": 2000,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt57ad7d924dac499c/652e711163a0f90d5e6a3bf3/MichiganState.svg?width=25&auto=webpll"
  },
  {
    "name": "Michigan Wolverines Basketball",
    "state": "MI",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 1989,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltec1c4d5cd251b3f4/652e6f79b6a603012c84fed9/Michigan.svg?width=25&auto=webpll"
  },
  {
    "name": "Ohio State Buckeyes Basketball",
    "state": "OH",
    "colors": "Red/Gray",
    "titles": 1,
    "lastTitle": 1960,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blte17cac83ffd34ecf/652e72377a7a16a3428bf7d1/OhioState.svg?width=25&auto=webpll"
  },
  {
    "name": "Wisconsin Badgers Basketball",
    "state": "WI",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1941,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt2de391bd391b1b05/652e70c9f465d39de273b728/Wisconsin.svg?width=25&auto=webpll"
  },
  {
    "name": "Maryland Terrapins Basketball",
    "state": "MD",
    "colors": "Red/Yellow",
    "titles": 1,
    "lastTitle": 2002,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt8fb34e720728a153/652e6fdb63a0f9efeb6a3bef/Maryland.svg?width=25&auto=webpll"
  },
  {
    "name": "Purdue Boilermakers Basketball",
    "state": "IN",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt7c26ab52bd6a820a/652e6ff37b318b9d89de4090/Purdue.svg?width=25&auto=webpll"
  },
  {
    "name": "Illinois Fighting Illini Basketball",
    "state": "IL",
    "colors": "Blue/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blta700e00f81b4f588/652e54ee5dde1055dfe83b21/Illinois.svg?width=25&auto=webpll"
  },
  {
    "name": "Iowa Hawkeyes Basketball",
    "state": "IA",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt808562b943ceb7fc/652e706db4a39a4e7cbba6c4/Iowa.svg?width=25&auto=webpll"
  },
  {
    "name": "Minnesota Golden Gophers Basketball",
    "state": "MN",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt1cfbfe21f5a53dfe/652e70e3926e87815fdf6180/Minnesota.svg?width=25&auto=webpll"
  },
  {
    "name": "Northwestern Wildcats Basketball",
    "state": "IL",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt9406ee350001b7f5/652e70ab28e5750b94c4d332/Northwestern.svg?width=25&auto=webpll"
  },
  {
    "name": "Nebraska Cornhuskers Basketball",
    "state": "NE",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt4e9259678abf417f/652e6f1aea588a1d98c0ae55/Nebraska.svg?width=25&auto=webpll"
  },
  {
    "name": "Rutgers Scarlet Knights Basketball",
    "state": "NJ",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltc1e5942c26218dbf/652e713cce77430b6242e062/Rutgers.svg?width=25&auto=webpll"
  },
  {
    "name": "Penn State Nittany Lions Basketball",
    "state": "PA",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt4f9c610bd3661dfe/652e71b228e57531f8c4d33c/PennState.svg?width=25&auto=webpll"
  },
  {
    "name": "UCLA Bruins Basketball",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 11,
    "lastTitle": 1995,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt6b9a5a27915d7928/66b3a4a4c5b50d82d7c27025/UCLA_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "USC Trojans Basketball",
    "state": "CA",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltba9a808e54dcab85/66b3a4921015920a003a9953/USC_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Oregon Ducks Basketball",
    "state": "OR",
    "colors": "Green/Yellow",
    "titles": 1,
    "lastTitle": 1939,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltb88e7fe1662a98ab/66b3a4b785938f6f1b5e1093/ORE_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Washington Huskies Basketball",
    "state": "WA",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Basketball",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blte423409d98d60ead/66b3a47e10159285c03a994d/WAS_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Florida Gators Basketball",
    "state": "FL",
    "colors": "Blue/Orange",
    "titles": 3,
    "lastTitle": 2025,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/7x70DtVylsw5z_-0takcoDcnBiLGKUZ6p7o5IfECPe4/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2U3OGI3YjBkLTQ2ZTEtNDk5YS1hYzQxLTkwNmRkNTYyYmRmMS5wbmc.png"
  },
  {
    "name": "Kentucky Wildcats Basketball",
    "state": "KY",
    "colors": "Blue/White",
    "titles": 8,
    "lastTitle": 2012,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/4Y_pFxzqIiIOu9X3q37gqPy_q9pfLAEmtpe3TVESQy0/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2Y4ZTQ5MTcxLTk3MmYtNGNkMy05YjM3LTczYzQ1ODFhM2JlMS5wbmc.png"
  },
  {
    "name": "Arkansas Razorbacks Basketball",
    "state": "AR",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1994,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/Httx4_v-r5cTkP8j2TeT262n3BhvYYYSoS-uxzcv5zY/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzZlMWMyNTcyLWEzZmEtNGY1Ny05MDc1LWU0MTlmNTY1ZWM5ZS5wbmc.png"
  },
  {
    "name": "LSU Tigers Basketball",
    "state": "LA",
    "colors": "Purple/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/KlulH7kuYDn9gXC0fhV1TiMkzcf2IEtJ3I-XhspTx3g/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzA5LzcwYmUyNTMxLWM4MjUtNGIwNi05ZWJlLWY1MDhlNmQyNjQxMS5wbmc.png"
  },
  {
    "name": "Alabama Crimson Tide Basketball",
    "state": "AL",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/59pezsMIwkFkWQwIteM8SkU0_8DtT7As5Zw1J1vhpC4/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzI2NGJiZDhlLTUyM2EtNDJkMC1iYjA1LWI2YjhmMzJjNzZlZS5wbmc.png"
  },
  {
    "name": "Tennessee Volunteers Basketball",
    "state": "TN",
    "colors": "Orange/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/N4P03EAVepUDsk5EBPzT8JbC7CbV5RG0PVHXm9Qm4LQ/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzczMGI4MDU2LWJmN2ItNDJmYS05OWIxLWFjMTU0Y2RiYjVlMy5wbmc.png"
  },
  {
    "name": "Auburn Tigers Basketball",
    "state": "AL",
    "colors": "Blue/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/KksghqjjiYLfUuVf5zsbzje9UOKW3HnS4iIsE7CwboU/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2Q5YjcwNWYzLTI3ZGUtNDdkMi1hNjhiLThkZjcwNTk2ZGY4ZC5wbmc.png"
  },
  {
    "name": "Mississippi State Bulldogs Basketball",
    "state": "MS",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/04/25/ae0ff859-70bd-415d-a198-aa3ccf079c5c.svg"
  },
  {
    "name": "Missouri Tigers Basketball",
    "state": "MO",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/47qh73f0zfVVqH60pXidQ0XYMGPw8F_g9CNyR2XOCmQ/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2IyMGM5OGU4LTczYzUtNGZlYi1iZDEzLTU3YTJlZGJmYjZkZS5wbmc.png"
  },
  {
    "name": "Ole Miss Rebels Basketball",
    "state": "MS",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/2GygXz4nt54y2SuRUtpaSqjn5vG0moyn9TCU3tIqWcE/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwLzdiNDBlY2VjLWUwYWMtNDRlZi05MDU1LWIxMWVkM2YyM2NmNS5wbmc.png"
  },
  {
    "name": "South Carolina Gamecocks Basketball",
    "state": "SC",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/Z1kBsodkv9qYtmLpjNMZoApBfgxZct6WVf6oIkgf4uU/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwLzlmMTdjYWIyLTRlZWYtNDk0NC04NjY4LWFkNmFmYjA1ZTJjMC5wbmc.png"
  },
  {
    "name": "Texas Longhorns Basketball",
    "state": "TX",
    "colors": "Orange/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/01/17/bb0ebd7f-a947-426e-8128-a8dd9f614738.svg"
  },
  {
    "name": "Texas A&M Aggies Basketball",
    "state": "TX",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/RRgkrFOBE1ujg8_a0DYU_t7POyi5nUoWdx6L9byhjOA/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzA5LzcwMjFmNWNiLTY3M2MtNGI3Mi1iY2NlLWI4MjhlOGI4OGJhZC5wbmc.png"
  },
  {
    "name": "Vanderbilt Commodores Basketball",
    "state": "TN",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/TYqkmorb-TUks57513hKDMs76-pfAgrcOuIGYnoSPws/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzI3LzgxNzU1NDVjLTE3MzAtNGI3My05MGZjLWYyM2ExMmY1Yzk3ZS5wbmc.png"
  },
  {
    "name": "Georgia Bulldogs Basketball",
    "state": "GA",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://www.secsports.com/imgproxy/WBESoSgTC8EjOpf0aAYaYpfI25EtSe3KJwa8ye6eukk/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwL2YyZGNlZGNiLWYxYjAtNDE5OC05OTBkLTg1NWQ1OTE0NWI4NS5wbmc.png"
  },
  {
    "name": "Oklahoma Sooners Basketball",
    "state": "OK",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Basketball",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/01/17/5c2e2d34-e5e4-4ca1-b004-71681a9836f1.svg"
  },
  {
    "name": "Duke Blue Devils Basketball",
    "state": "NC",
    "colors": "Blue/White",
    "titles": 5,
    "lastTitle": 2015,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/33423e84-1594-6373-1025-20cdd256c421/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "North Carolina Tar Heels Basketball",
    "state": "NC",
    "colors": "Blue/White",
    "titles": 6,
    "lastTitle": 2017,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/North_Carolina_Tar_Heels_logo.svg/1200px-North_Carolina_Tar_Heels_logo.svg.png"
  },
  {
    "name": "NC State Wolfpack Basketball",
    "state": "NC",
    "colors": "Red/White",
    "titles": 2,
    "lastTitle": 1983,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/1a66a197-258b-8ac5-56f9-6f4b6ec4d4ed/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "Virginia Cavaliers Basketball",
    "state": "VA",
    "colors": "Blue/Orange",
    "titles": 1,
    "lastTitle": 2019,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/61451359-15ec-b9ff-6584-ca6254971797/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Syracuse Orange Basketball",
    "state": "NY",
    "colors": "Blue/Orange",
    "titles": 1,
    "lastTitle": 2003,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/8a53c7d6-5f95-d1c0-ed4e-374f53b04443/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Boston College Eagles Basketball",
    "state": "MA",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/4abb970f-c9e6-7576-3daa-703957b91293/logos/primary_logo_on_secondary_color.png"
  },
  {
    "name": "California Golden Bears Basketball",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 1959,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/bc456bd2-12dc-1f16-79d5-da8899277a32/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Clemson Tigers Basketball",
    "state": "SC",
    "colors": "Purple/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/02382072-a5a3-24ff-6bd1-422a029bd33c/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Florida State Seminoles Basketball",
    "state": "FL",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/fa181128-4809-a209-1add-d5a3b0cefd3c/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Georgia Tech Yellow Jackets Basketball",
    "state": "GA",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/e2e3ae48-f880-5489-0628-b2286d0adca1/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Louisville Cardinals Basketball",
    "state": "KS",
    "colors": "Black/Red",
    "titles": 3,
    "lastTitle": 2013,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/0584f11f-3e1c-d2ac-b852-35a74216c53e/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Miami Hurricanes Basketball",
    "state": "FL",
    "colors": "Green/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/2b3657a5-caae-31a2-899a-0d09df0f7bed/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Notre Dame Fighting Irish Basketball",
    "state": "IN",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/ebc2999c-2ff4-8435-ca46-9641e9f9ea10/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Pittsburgh Panthers Basketball",
    "state": "PA",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/f09e85bd-989f-dcff-53ac-0feda69b8959/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "SMU Mustangs Basketball",
    "state": "TX",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/1ca864c9-0072-57e4-6fbf-d333f53e4409/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Stanford Cardinal Basketball",
    "state": "CA",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1942,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/f74a44c4-7492-7a6e-34fe-ab14da6d7f2a/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Virginia Tech Hokies Basketball",
    "state": "VA",
    "colors": "Red/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/2adbb165-47c5-a0c4-aba8-26fa5d1302de/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Wake Forest Demon Deacons Basketball",
    "state": "NC",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/f6a988be-475f-6cad-3569-47b6803c25cb/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Kansas Jayhawks Basketball",
    "state": "KS",
    "colors": "Blue/Red",
    "titles": 4,
    "lastTitle": 2022,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/83fb6648-677a-1a40-715d-5fa16287399a/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Baylor Bears Basketball",
    "state": "TX",
    "colors": "Green/Yellow",
    "titles": 1,
    "lastTitle": 2021,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/f09699d9-0894-3cf9-c5e4-cb392dfb72b8/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Oklahoma State Cowboys Basketball",
    "state": "OK",
    "colors": "Black/Orange",
    "titles": 2,
    "lastTitle": 1946,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/556bcca7-0c38-f441-d76f-13bf46ff4042/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Arizona Wildcats Basketball",
    "state": "AZ",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 1997,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/c845c06f-f087-b63d-1bcc-8013bd715b59/logos/secondary_logo_on_black_color.png"
  },
  {
    "name": "Arizona State Sun Devils Basketball",
    "state": "AZ",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/d60a0d84-8fa8-2bdf-13ec-fb0f9deda94c/logos/primary_logo_on_secondary_color.png"
  },
  {
    "name": "BYU Cougars Basketball",
    "state": "UT",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/fd2097de-a7e2-47ee-cc8a-e215a2b104c4/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Cincinnati Bearcats Basketball",
    "state": "OH",
    "colors": "Black/Red",
    "titles": 2,
    "lastTitle": 1962,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://static.wikia.nocookie.net/collegefootballmania/images/4/41/Cincinnati-Bearcats-Logo.png/revision/latest?cb=20240514030256"
  },
  {
    "name": "Colorado Buffaloes Basketball",
    "state": "CO",
    "colors": "Black/Gray",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/78bdee7f-11f2-3bf9-f93e-a8e3831c2792/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Houston Cougars Basketball",
    "state": "TX",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/508c397e-91bb-ed5c-a21c-d8faf8726265/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Iowa State Cyclones Basketball",
    "state": "IA",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/98f92ad4-696c-890b-02e0-f7609d89e38c/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "Kansas State Wildcats Basketball",
    "state": "KS",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/b82ceb2c-b0bc-16f8-4cdb-d038df734db4/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "TCU Horned Frogs Basketball",
    "state": "TX",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/ff514898-e802-ac6e-d4ef-94b617a48656/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Texas Tech Red Raiders Basketball",
    "state": "TX",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/4350bc91-1a0d-8292-bf66-9687147703f0/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "UCF Knights Basketball",
    "state": "FL",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/c9803f48-33e7-2ff2-03ef-ca6c319e1787/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Utah Utes Basketball",
    "state": "UT",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1944,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/8dbdf443-6ffa-7a66-b58f-c0a7484ead29/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "West Virginia Mountaineers Basketball",
    "state": "WV",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/e5ca2c6f-2389-9da3-43cd-995fad2e06c5/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "UConn Huskies Basketball",
    "state": "CT",
    "colors": "Blue/White",
    "titles": 6,
    "lastTitle": 2024,
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/c7561e25-c7f2-5ddd-4191-899a98236d54/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Villanova Wildcats Basketball",
    "state": "PA",
    "colors": "Blue/White",
    "titles": 3,
    "lastTitle": 2018,
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/12df2e93-a8a5-389b-e71e-cedcbb195558/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Georgetown Hoyas Basketball",
    "state": "DC",
    "colors": "Blue/Gray",
    "titles": 1,
    "lastTitle": 1984,
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/8544eb4d-057a-3a03-aece-512fb2b9437c/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Marquette Golden Eagles Basketball",
    "state": "WI",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 1977,
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/031f4755-6d7f-61c5-842c-9460a695085b/logos/secondary_logo_on_black_color.png"
  },
  {
    "name": "Providence Friars Basketball",
    "state": "RI",
    "colors": "Black/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/dba43170-9fc2-c859-6e26-dc482aee8c9f/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Seton Hall Pirates Basketball",
    "state": "NJ",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/045e28ba-b8f3-15e8-f84c-f3ca7e2c32fb/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "St. John's Red Storm Basketball",
    "state": "NY",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/ff52cb9b-b02b-9bdb-6e1b-48a7ff8f6c5d/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Xavier Musketeers Basketball",
    "state": "OH",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/b1bf5c27-708e-7306-b08e-5b34154e261d/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Butler Bulldogs Basketball",
    "state": "IN",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRARdoosx3mSgKFJHQzuXiaRKtEPXa2FsaQBw&s"
  },
  {
    "name": "Creighton Bluejays Basketball",
    "state": "NE",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/fee02fb1-fabd-2194-4f76-ea4fc944faa3/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "DePaul Blue Demons Basketball",
    "state": "IL",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big East",
    "sport": "Basketball",
    "logo": "https://a.espncdn.com/guid/42e7dd20-f9ef-e815-b28d-db6da936bc5d/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "Indiana Hoosiers Football",
    "state": "IN",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt642e368419deffde/652e7097926e8748efdf617e/Indiana.svg?width=25&auto=webpll"
  },
  {
    "name": "Michigan State Spartans Football",
    "state": "MI",
    "colors": "Green/White",
    "titles": 6,
    "lastTitle": 1966,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt57ad7d924dac499c/652e711163a0f90d5e6a3bf3/MichiganState.svg?width=25&auto=webpll"
  },
  {
    "name": "Michigan Wolverines Football",
    "state": "MI",
    "colors": "Blue/Yellow",
    "titles": 12,
    "lastTitle": 2023,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltec1c4d5cd251b3f4/652e6f79b6a603012c84fed9/Michigan.svg?width=25&auto=webpll"
  },
  {
    "name": "Ohio State Buckeyes Football",
    "state": "OH",
    "colors": "Red/Gray",
    "titles": 9,
    "lastTitle": 2014,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blte17cac83ffd34ecf/652e72377a7a16a3428bf7d1/OhioState.svg?width=25&auto=webpll"
  },
  {
    "name": "Wisconsin Badgers Football",
    "state": "WI",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt2de391bd391b1b05/652e70c9f465d39de273b728/Wisconsin.svg?width=25&auto=webpll"
  },
  {
    "name": "Maryland Terrapins Football",
    "state": "MD",
    "colors": "Red/Yellow",
    "titles": 1,
    "lastTitle": 1953,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt8fb34e720728a153/652e6fdb63a0f9efeb6a3bef/Maryland.svg?width=25&auto=webpll"
  },
  {
    "name": "Purdue Boilermakers Football",
    "state": "IN",
    "colors": "Black/Yellow",
    "titles": 1,
    "lastTitle": 1931,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt7c26ab52bd6a820a/652e6ff37b318b9d89de4090/Purdue.svg?width=25&auto=webpll"
  },
  {
    "name": "Illinois Fighting Illini Football",
    "state": "IL",
    "colors": "Blue/Orange",
    "titles": 5,
    "lastTitle": 1951,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blta700e00f81b4f588/652e54ee5dde1055dfe83b21/Illinois.svg?width=25&auto=webpll"
  },
  {
    "name": "Iowa Hawkeyes Football",
    "state": "IA",
    "colors": "Black/Yellow",
    "titles": 5,
    "lastTitle": 1960,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt808562b943ceb7fc/652e706db4a39a4e7cbba6c4/Iowa.svg?width=25&auto=webpll"
  },
  {
    "name": "Minnesota Golden Gophers Football",
    "state": "MN",
    "colors": "Red/Yellow",
    "titles": 7,
    "lastTitle": 1960,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt1cfbfe21f5a53dfe/652e70e3926e87815fdf6180/Minnesota.svg?width=25&auto=webpll"
  },
  {
    "name": "Northwestern Wildcats Football",
    "state": "IL",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt9406ee350001b7f5/652e70ab28e5750b94c4d332/Northwestern.svg?width=25&auto=webpll"
  },
  {
    "name": "Nebraska Cornhuskers Football",
    "state": "NE",
    "colors": "Red/White",
    "titles": 5,
    "lastTitle": 1997,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt4e9259678abf417f/652e6f1aea588a1d98c0ae55/Nebraska.svg?width=25&auto=webpll"
  },
  {
    "name": "Rutgers Scarlet Knights Football",
    "state": "NJ",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1869,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltc1e5942c26218dbf/652e713cce77430b6242e062/Rutgers.svg?width=25&auto=webpll"
  },
  {
    "name": "Penn State Nittany Lions Football",
    "state": "PA",
    "colors": "Blue/White",
    "titles": 2,
    "lastTitle": 1986,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt4f9c610bd3661dfe/652e71b228e57531f8c4d33c/PennState.svg?width=25&auto=webpll"
  },
  {
    "name": "UCLA Bruins Football",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 1,
    "lastTitle": 1954,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blt6b9a5a27915d7928/66b3a4a4c5b50d82d7c27025/UCLA_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "USC Trojans Football",
    "state": "CA",
    "colors": "Red/Yellow",
    "titles": 11,
    "lastTitle": 2004,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltba9a808e54dcab85/66b3a4921015920a003a9953/USC_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Oregon Ducks Football",
    "state": "OR",
    "colors": "Green/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/bltb88e7fe1662a98ab/66b3a4b785938f6f1b5e1093/ORE_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Washington Huskies Football",
    "state": "WA",
    "colors": "Purple/White",
    "titles": 2,
    "lastTitle": 1991,
    "league": "NCAA",
    "conference": "Big Ten",
    "sport": "Football",
    "logo": "https://dxln3ux406vra.cloudfront.net/v3/assets/bltca750cef518bc6e4/blte423409d98d60ead/66b3a47e10159285c03a994d/WAS_Primary.svg?width=25&auto=webpll"
  },
  {
    "name": "Florida Gators Football",
    "state": "FL",
    "colors": "Blue/Orange",
    "titles": 3,
    "lastTitle": 2008,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/7x70DtVylsw5z_-0takcoDcnBiLGKUZ6p7o5IfECPe4/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2U3OGI3YjBkLTQ2ZTEtNDk5YS1hYzQxLTkwNmRkNTYyYmRmMS5wbmc.png"
  },
  {
    "name": "Kentucky Wildcats Football",
    "state": "KY",
    "colors": "Blue/White",
    "titles": 1,
    "lastTitle": 1950,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/4Y_pFxzqIiIOu9X3q37gqPy_q9pfLAEmtpe3TVESQy0/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2Y4ZTQ5MTcxLTk3MmYtNGNkMy05YjM3LTczYzQ1ODFhM2JlMS5wbmc.png"
  },
  {
    "name": "Arkansas Razorbacks Football",
    "state": "AR",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1964,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/Httx4_v-r5cTkP8j2TeT262n3BhvYYYSoS-uxzcv5zY/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzZlMWMyNTcyLWEzZmEtNGY1Ny05MDc1LWU0MTlmNTY1ZWM5ZS5wbmc.png"
  },
  {
    "name": "LSU Tigers Football",
    "state": "LA",
    "colors": "Purple/Yellow",
    "titles": 4,
    "lastTitle": 2019,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/KlulH7kuYDn9gXC0fhV1TiMkzcf2IEtJ3I-XhspTx3g/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzA5LzcwYmUyNTMxLWM4MjUtNGIwNi05ZWJlLWY1MDhlNmQyNjQxMS5wbmc.png"
  },
  {
    "name": "Alabama Crimson Tide Football",
    "state": "AL",
    "colors": "Red/White",
    "titles": 18,
    "lastTitle": 2020,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/59pezsMIwkFkWQwIteM8SkU0_8DtT7As5Zw1J1vhpC4/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzI2NGJiZDhlLTUyM2EtNDJkMC1iYjA1LWI2YjhmMzJjNzZlZS5wbmc.png"
  },
  {
    "name": "Tennessee Volunteers Football",
    "state": "TN",
    "colors": "Orange/White",
    "titles": 2,
    "lastTitle": 1998,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/N4P03EAVepUDsk5EBPzT8JbC7CbV5RG0PVHXm9Qm4LQ/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5LzczMGI4MDU2LWJmN2ItNDJmYS05OWIxLWFjMTU0Y2RiYjVlMy5wbmc.png"
  },
  {
    "name": "Auburn Tigers Football",
    "state": "AL",
    "colors": "Blue/Orange",
    "titles": 2,
    "lastTitle": 2010,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/KksghqjjiYLfUuVf5zsbzje9UOKW3HnS4iIsE7CwboU/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2Q5YjcwNWYzLTI3ZGUtNDdkMi1hNjhiLThkZjcwNTk2ZGY4ZC5wbmc.png"
  },
  {
    "name": "Mississippi State Bulldogs Football",
    "state": "MS",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/04/25/ae0ff859-70bd-415d-a198-aa3ccf079c5c.svg"
  },
  {
    "name": "Missouri Tigers Football",
    "state": "MO",
    "colors": "Black/Yellow",
    "titles": 2,
    "lastTitle": 1960,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/47qh73f0zfVVqH60pXidQ0XYMGPw8F_g9CNyR2XOCmQ/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzA5L2IyMGM5OGU4LTczYzUtNGZlYi1iZDEzLTU3YTJlZGJmYjZkZS5wbmc.png"
  },
  {
    "name": "Ole Miss Rebels Football",
    "state": "MS",
    "colors": "Blue/Red",
    "titles": 3,
    "lastTitle": 1960,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/2GygXz4nt54y2SuRUtpaSqjn5vG0moyn9TCU3tIqWcE/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwLzdiNDBlY2VjLWUwYWMtNDRlZi05MDU1LWIxMWVkM2YyM2NmNS5wbmc.png"
  },
  {
    "name": "South Carolina Gamecocks Football",
    "state": "SC",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/Z1kBsodkv9qYtmLpjNMZoApBfgxZct6WVf6oIkgf4uU/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwLzlmMTdjYWIyLTRlZWYtNDk0NC04NjY4LWFkNmFmYjA1ZTJjMC5wbmc.png"
  },
  {
    "name": "Texas Longhorns Football",
    "state": "TX",
    "colors": "Orange/White",
    "titles": 4,
    "lastTitle": 2005,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/01/17/bb0ebd7f-a947-426e-8128-a8dd9f614738.svg"
  },
  {
    "name": "Texas A&M Aggies Football",
    "state": "TX",
    "colors": "Red/White",
    "titles": 1,
    "lastTitle": 1939,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/RRgkrFOBE1ujg8_a0DYU_t7POyi5nUoWdx6L9byhjOA/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzA5LzcwMjFmNWNiLTY3M2MtNGI3Mi1iY2NlLWI4MjhlOGI4OGJhZC5wbmc.png"
  },
  {
    "name": "Vanderbilt Commodores Football",
    "state": "TN",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/TYqkmorb-TUks57513hKDMs76-pfAgrcOuIGYnoSPws/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDIzLzExLzI3LzgxNzU1NDVjLTE3MzAtNGI3My05MGZjLWYyM2ExMmY1Yzk3ZS5wbmc.png"
  },
  {
    "name": "Georgia Bulldogs Football",
    "state": "GA",
    "colors": "Black/Red",
    "titles": 4,
    "lastTitle": 2022,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://www.secsports.com/imgproxy/WBESoSgTC8EjOpf0aAYaYpfI25EtSe3KJwa8ye6eukk/rs:fit:1150:0:0:g:ce/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NlY3Nwb3J0cy1wcm9kL3VwbG9hZC8yMDI0LzAxLzEwL2YyZGNlZGNiLWYxYjAtNDE5OC05OTBkLTg1NWQ1OTE0NWI4NS5wbmc.png"
  },
  {
    "name": "Oklahoma Sooners Football",
    "state": "OK",
    "colors": "Red/White",
    "titles": 7,
    "lastTitle": 2000,
    "league": "NCAA",
    "conference": "SEC",
    "sport": "Football",
    "logo": "https://storage.googleapis.com/secsports-prod/upload/2024/01/17/5c2e2d34-e5e4-4ca1-b004-71681a9836f1.svg"
  },
  {
    "name": "Duke Blue Devils Football",
    "state": "NC",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/33423e84-1594-6373-1025-20cdd256c421/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "North Carolina Tar Heels Football",
    "state": "NC",
    "colors": "Blue/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/North_Carolina_Tar_Heels_logo.svg/1200px-North_Carolina_Tar_Heels_logo.svg.png"
  },
  {
    "name": "NC State Wolfpack Football",
    "state": "NC",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/1a66a197-258b-8ac5-56f9-6f4b6ec4d4ed/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "Virginia Cavaliers Football",
    "state": "VA",
    "colors": "Blue/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/61451359-15ec-b9ff-6584-ca6254971797/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Syracuse Orange Football",
    "state": "NY",
    "colors": "Blue/Orange",
    "titles": 1,
    "lastTitle": 1959,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/8a53c7d6-5f95-d1c0-ed4e-374f53b04443/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Boston College Eagles Football",
    "state": "MA",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/4abb970f-c9e6-7576-3daa-703957b91293/logos/primary_logo_on_secondary_color.png"
  },
  {
    "name": "California Golden Bears Football",
    "state": "CA",
    "colors": "Blue/Yellow",
    "titles": 5,
    "lastTitle": 1937,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/bc456bd2-12dc-1f16-79d5-da8899277a32/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Clemson Tigers Football",
    "state": "SC",
    "colors": "Purple/Orange",
    "titles": 3,
    "lastTitle": 2018,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/02382072-a5a3-24ff-6bd1-422a029bd33c/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Florida State Seminoles Football",
    "state": "FL",
    "colors": "Red/Yellow",
    "titles": 3,
    "lastTitle": 2013,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/fa181128-4809-a209-1add-d5a3b0cefd3c/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Georgia Tech Yellow Jackets Football",
    "state": "GA",
    "colors": "Blue/Yellow",
    "titles": 4,
    "lastTitle": 1990,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/e2e3ae48-f880-5489-0628-b2286d0adca1/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Louisville Cardinals Football",
    "state": "KS",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/0584f11f-3e1c-d2ac-b852-35a74216c53e/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Miami Hurricanes Football",
    "state": "FL",
    "colors": "Green/Orange",
    "titles": 5,
    "lastTitle": 2001,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/2b3657a5-caae-31a2-899a-0d09df0f7bed/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Pittsburgh Panthers Football",
    "state": "PA",
    "colors": "Blue/Yellow",
    "titles": 9,
    "lastTitle": 1976,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/f09e85bd-989f-dcff-53ac-0feda69b8959/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "SMU Mustangs Football",
    "state": "TX",
    "colors": "Blue/Red",
    "titles": 1,
    "lastTitle": 1935,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/1ca864c9-0072-57e4-6fbf-d333f53e4409/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Stanford Cardinal Football",
    "state": "CA",
    "colors": "Red/White",
    "titles": 2,
    "lastTitle": 1940,
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/f74a44c4-7492-7a6e-34fe-ab14da6d7f2a/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Virginia Tech Hokies Football",
    "state": "VA",
    "colors": "Red/Orange",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/2adbb165-47c5-a0c4-aba8-26fa5d1302de/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Wake Forest Demon Deacons Football",
    "state": "NC",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "ACC",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/f6a988be-475f-6cad-3569-47b6803c25cb/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Kansas Jayhawks Football",
    "state": "KS",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/83fb6648-677a-1a40-715d-5fa16287399a/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Baylor Bears Football",
    "state": "TX",
    "colors": "Green/Yellow",
    "titles": 1,
    "lastTitle": 1974,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/f09699d9-0894-3cf9-c5e4-cb392dfb72b8/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Oklahoma State Cowboys Football",
    "state": "OK",
    "colors": "Black/Orange",
    "titles": 1,
    "lastTitle": 1945,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/556bcca7-0c38-f441-d76f-13bf46ff4042/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Arizona Wildcats Football",
    "state": "AZ",
    "colors": "Blue/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/c845c06f-f087-b63d-1bcc-8013bd715b59/logos/secondary_logo_on_black_color.png"
  },
  {
    "name": "Arizona State Sun Devils Football",
    "state": "AZ",
    "colors": "Red/Yellow",
    "titles": 2,
    "lastTitle": 1975,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/d60a0d84-8fa8-2bdf-13ec-fb0f9deda94c/logos/primary_logo_on_secondary_color.png"
  },
  {
    "name": "BYU Cougars Football",
    "state": "UT",
    "colors": "Blue/White",
    "titles": 1,
    "lastTitle": 1984,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/fd2097de-a7e2-47ee-cc8a-e215a2b104c4/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Cincinnati Bearcats Football",
    "state": "OH",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://static.wikia.nocookie.net/collegefootballmania/images/4/41/Cincinnati-Bearcats-Logo.png/revision/latest?cb=20240514030256"
  },
  {
    "name": "Colorado Buffaloes Football",
    "state": "CO",
    "colors": "Black/Gray",
    "titles": 1,
    "lastTitle": 1990,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/78bdee7f-11f2-3bf9-f93e-a8e3831c2792/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Houston Cougars Football",
    "state": "TX",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/508c397e-91bb-ed5c-a21c-d8faf8726265/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Iowa State Cyclones Football",
    "state": "IA",
    "colors": "Red/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/98f92ad4-696c-890b-02e0-f7609d89e38c/logos/primary_logo_on_primary_color.png"
  },
  {
    "name": "Kansas State Wildcats Football",
    "state": "KS",
    "colors": "Purple/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/b82ceb2c-b0bc-16f8-4cdb-d038df734db4/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "TCU Horned Frogs Football",
    "state": "TX",
    "colors": "Purple/White",
    "titles": 2,
    "lastTitle": 1938,
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/ff514898-e802-ac6e-d4ef-94b617a48656/logos/primary_logo_on_white_color.png"
  },
  {
    "name": "Texas Tech Red Raiders Football",
    "state": "TX",
    "colors": "Black/Red",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/4350bc91-1a0d-8292-bf66-9687147703f0/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "UCF Knights Football",
    "state": "FL",
    "colors": "Black/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/c9803f48-33e7-2ff2-03ef-ca6c319e1787/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "Utah Utes Football",
    "state": "UT",
    "colors": "Red/White",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/8dbdf443-6ffa-7a66-b58f-c0a7484ead29/logos/primary_logo_on_black_color.png"
  },
  {
    "name": "West Virginia Mountaineers Football",
    "state": "WV",
    "colors": "Blue/Yellow",
    "titles": 0,
    "lastTitle": "None",
    "league": "NCAA",
    "conference": "Big 12",
    "sport": "Football",
    "logo": "https://a.espncdn.com/guid/e5ca2c6f-2389-9da3-43cd-995fad2e06c5/logos/primary_logo_on_white_color.png"
  }
]